name = "Kaapi"
license = "MIT"
licenselink = "https://github.com/satiyap/kaapi/blob/main/LICENSE"
description = "A minimal, responsive Hugo theme inspired by filter coffee—focused, clean, and crafted with patience"
homepage = "https://github.com/satiyap/kaapi"
demosite = "https://github.com/satiyap/kaapi"
tags = ["blog", "minimal", "responsive", "clean", "coffee", "single-author"]
features = ["responsive", "minimal", "blog", "clean-design", "single-author", "toc"]
min_version = "0.146.0"

[author]
  name = "satiyap"
  homepage = "https://github.com/satiyap"
